apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-example-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/deepakraj5/argocd-app.git
    targetRevision: HEAD
    path: /manifest
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false