apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-app-certificate
spec:
  secretName: example-app-secret-key
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - deepakdev
  dnsNames:
  - deepakdev.me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io